### PR TITLE
Optimize dockerfiles docker-compose

### LINKED ISSUE #56: Dockerize the Application
**Current Behavior**
The application is not having Dockerfiles 

**Desired Behavior**
Application should run inside Docker Container

**Proposed Solution**
I will add Dockerfiles and dockercompose.yml files to the application

**Additional Context**
Containerizing an application using Docker enhances portability, scalability, and efficiency by isolating dependencies, ensuring consistent environments across platforms, and simplifying deployment, management, and scaling in cloud-native environments.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
### All Submissions:

fixes #56 

- [X] Have you followed the guidelines stated in [README.md](https://github.com/visheshrwl/Uber-like/tree
/main#how-to-contribute) file?
- [X] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/visheshrwl/Uber-like/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Optimizes docker setup
    b. Additions in dockerfiles and docker-compose, built  a network for all the sevices to talk to each other, fixed reditClient Intialization as it had error from outdated syntax.

    c. fixes #56

### CODE REVIEW

**Comment by haseebzaki-07** [comment]
hey @visheshrwl please add the gssoc-ext and level tags

**Comment by haseebzaki-07** [comment]
level??

**Comment by visheshrwl** [comment]
Hey @haseebzaki-07 ! 👋

First off, I want to extend a huge thank you to all of you for your amazing contributions to this project! Your support and hard work mean a lot, and I truly appreciate everything you do. 🙏

I have a small favor to ask: if you think I’ve been helpful and supportive throughout your contributions, I would be honored if you could nominate me by filling out this form: [Nominate me](https://docs.google.com/forms/d/e/1FAIpQLSdnqJ5crpQFQEQXGTzekfKUxOJCXkSx8AykqvvHzlqBcNGMAQ/viewform).

Your nomination would mean the world to me, and it’s a great way to help me continue supporting our awesome community. Thanks again for all the amazing work, and let's keep making great things happen! 🚀

Best,
Vishesh

**Comment by haseebzaki-07** [comment]
Sure @visheshrwl It was really amazing experience for me working with you.

Will definitely nominate you.

**Pull request merged**
