### PR TITLE
[Documentation] : Enhancement Of Contributing.md

### PR DESCRIPTION
**Pull request by milansamuel609**
### All Submissions:

- [x] Have you followed the guidelines stated in [README.md](https://github.com/visheshrwl/Uber-like/tree
/main#how-to-contribute) file?
- [x] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/visheshrwl/Uber-like/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [x] Documentation Update

### **After** these steps, you're ready to open a pull request.

a. Enhancements of Contributing.md file

b. I have enhanced the document and also added some new sections

Done the following changes :-

1) Enhanced the project structure
2) Added star our repository section
3) Added first pull request steps section
4) Added good coding practices section
5) Added the pull request rules section
6) Added the thank you section

c. Closes:[#64 ]

image

image

image

image

image

### CODE REVIEW

**Comment by milansamuel609** [comment]
I have done enhancements in the documentation. Please kindly check once, if all things are fine please merge the PR. Also please attach the gssoc extend and level label.

**Review by visheshrwl — CHANGES_REQUESTED** [review]
Hey @milansamuel609 , thanks for contributing! For now, could you please just add the section you'd like without altering the current readme sections?

**Comment by milansamuel609** [comment]
Actually I have already done my changes and not changed the previous changes which were already there

**Comment by milansamuel609** [comment]
If all the changes are fine please kindly merge the PR. Also please add the gssoc extend and level label.

**Comment by visheshrwl** [comment]
Hey @milansamuel609 ! 👋

First off, I want to extend a huge thank you to all of you for your amazing contributions to this project! Your support and hard work mean a lot, and I truly appreciate everything you do. 🙏

I have a small favor to ask: if you think I’ve been helpful and supportive throughout your contributions, I would be honored if you could nominate me by filling out this form: [Nominate me](https://docs.google.com/forms/d/e/1FAIpQLSdnqJ5crpQFQEQXGTzekfKUxOJCXkSx8AykqvvHzlqBcNGMAQ/viewform).

Your nomination would mean the world to me, and it’s a great way to help me continue supporting our awesome community. Thanks again for all the amazing work, and let's keep making great things happen! 🚀

Best,
Vishesh

**Pull request merged**
