### PR TITLE
Integration of Advanced Routing Algorithms

### LINKED ISSUE #47: Integration of Advanced Routing Algorithms
**Is your feature request related to a problem? Please describe.**
Integrate advanced routing algorithms to optimize driver paths and reduce ride time.

**Additional context**
- Connect to backend routing API for optimized route suggestions.
- Update the UI to reflect real-time route changes.
- Show ETA and route details to the user.

### PR DESCRIPTION
**Pull request by haseebzaki-07**
### All Submissions:

- [X] Have you followed the guidelines stated in [README.md](https://github.com/visheshrwl/Uber-like/tree
/main#how-to-contribute) file?
- [X] Have you checked to ensure there aren't any other open [Pull Requests](https://github.com/visheshrwl/Uber-like/pulls) for the desired changed?

### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### **After** these steps, you're ready to open a pull request.

    a. Created the backend API for the routign algorithm. Integrated the frontend to show the ETA timings.

    b. closes #47

### CODE REVIEW

**Review by visheshrwl — CHANGES_REQUESTED** [review]
@haseebzaki-07 , great start! There are a few areas for improvement to make the PR more robust and scalable:

1. **Request Validation**  
   `req.body.start` and `req.body.end` are used without validation, which could cause runtime errors if the input is missing or improperly structured. Consider using a validation library like **Joi** or **Zod** to validate these inputs. This will ensure the API only processes properly formatted requests.

2. **Error Handling & Logging**  
   The current error handling is quite basic. Adding a custom error-handling middleware and structured logging would help capture detailed error information, making debugging easier and improving the user experience.

3. **Separation of Concerns**  
   The Google Maps API call is tightly coupled within the route handler. Moving this logic into a separate service file (e.g., `googleMapsService.js`) will improve code organization and readability.

4. **Caching**  
   Repeated calls to external APIs, such as Google Maps, can lead to rate limits and cost overhead. Implement a caching layer, like **Redis**, to store the results of recent requests. This can significantly improve response times and reduce dependency on the external API.

5. **API Versioning**  
   To facilitate future changes and backward compatibility, consider adding versioning to the endpoint (e.g., `/api/v1/optimize-route`). This will make it easier to introduce changes without breaking existing clients.

Let me know if you need any examples or additional guidance on these points!

**Comment by haseebzaki-07** [comment]
@visheshrwl I will update with the changes.

**Comment by haseebzaki-07** [comment]
Hey @visheshrwl made almost all the changes mentioned above.

**Comment by haseebzaki-07** [comment]
Hey @visheshrwl please add the labels to this PR

**Pull request merged**
